# https://kubernetes.io/zh/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-claim # claimName
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
