apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-deployment-config
data:
  404.html: |
    <html>
    	<body>404</body>
    </html>

  nginx.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   404              /404.html;
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
