apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  selector:   # ReplicaSet 组成部分
    matchLabels:
      app: nginx-alpine
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
      - name: nginx-alpine
        image: nginx:alpine
        ports:
        - containerPort: 80
