version: '3.3'  # To use file based secrets.

services:
  jenkins-lts-jdk11:
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      # HOST:CONTAINER
      - '80:8080'
    environment:
      - 'JAVA_OPTS=-Xms2048m -Xmx3072m'
    volumes:
      - 'jenkins_home_lts_jdk11_proxy:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/:/root/'
    network_mode: "bridge"
volumes:
  # compose_jenkins_home_lts_jdk11
  jenkins_home_lts_jdk11:
  # compose_jenkins_home_lts_jdk11_proxy
  jenkins_home_lts_jdk11_proxy:
