version: '3.3'  # To use file based secrets.

services:

  jenkins-lts-jdk11:
    image: ma3310/jenkins:lts-jdk11-tools
    restart: unless-stopped
    ports:
      # HOST:CONTAINER
      - '80:8080'
    environment:
      - 'JAVA_OPTS=-Xms2048m -Xmx3072m '
    volumes:
      # chown -R 1000:1000 ./data/jenkins_home
      - './data/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$HOME:/root'
# network_mode: "host"
