version: "3.6"
# 如何使用环境变量 https://docs.docker.com/compose/compose-file/#variable-substitution

services:
    mysql:
        image: "mysql:5.7"
        restart: always
        container_name: "${PREFIX_NAME}_mysql-5.7"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/root:/var/lib/mysql
        ports:
            - 3306
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        restart: always
        container_name: "${PREFIX_NAME}_phpmyadmin"
        environment:
            #- PMA_ARBITRARY=1
            PMA_HOST: "${PREFIX_NAME}_mysql-5.7"
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        ports:
            - 80
        depends_on: 
            - mysql

