apiVersion: v1
kind: Pod
metadata:
  name: busybox-httpd
  namespace: default
spec:
  containers:
    - name: busybox-httpd
      image: busybox
      resources:
        requests:
          memory: "128Mi"
          cpu: "0.5"
        limits:
          memory: "512Mi"
          cpu: "1"
      command:
        - httpd
        - '-f'
