# Deployed the service in bridge and map http port to host 8080.
version: "3.3"  # To use file based secrets.

services:

    tomcat-9-jdk8:
        image: "tomcat:9-jdk8"
        restart: unless-stopped
        volumes:
            - ./conf/:/usr/local/tomcat/conf/
            - ./apps/:/usr/local/tomcat/webapps/
            - ./logs/:/usr/local/tomcat/logs/
        ports:
            # Change host port to suitable value.
            - "8080:8080"  # HOST:CONTAINER
        networks:
            - default
