# docker-compose uses local as volume: https://github.com/docker/compose/issues/2957
version: "3.3"

services:
    mod_auth_openidc-2.3.11:
        image: "ma3310/centos:6-oidc-2.3.11"
        restart: always
        volumes: 
            - ./etc/httpd/conf:/opt/rh/httpd24/root/etc/httpd/conf
            - ./etc/httpd/conf.d:/opt/rh/httpd24/root/etc/httpd/conf.d
            - ./etc/httpd/conf.modules.d:/opt/rh/httpd24/root/etc/httpd/conf.modules.d
        ports:
            - 80
            - 443
        network_mode: "host"
