version: "3.1"

services:
    mysql:
        image: "mysql:5.7"
        container_name: "mysql-5.7"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/devel:/var/lib/mysql
        ports:
            - 3306
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        restart: always
        environment:
            #- PMA_ARBITRARY=1
            PMA_HOST: "mysql-5.7"
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        ports:
            - 80
        depends_on: 
            - mysql

