# Deployed the service in bridge then map port to host.
version: "3.3"  # To use file based secrets.

services:

    # ModSecurity/nginx on 80/443 port.
    modsecurity-crs-3.3-nginx:
        image: "owasp/modsecurity-crs:3.3-nginx"
        restart: unless-stopped
        ports:
            - "80:80"        # HOST:CONTAINER
            - "443:443"      # HOST:CONTAINER    
        environment:    # Type: Object
            TZ: Asia/Shanghai
        volumes:
            # Inject Whit IPs.
            - ./conf/modsecurity.d/modsecurity-ip-whitelist.conf:/etc/modsecurity.d/modsecurity-ip-whitelist.conf
            - ./conf/modsecurity.d/setup.conf:/etc/modsecurity.d/setup.conf
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./logs:/var/log
            - ./logs/nginx:/var/log/nginx
            - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - default
