# Deployed the service in bridge then map port to host.
version: "3.3"  # To use file based secrets.

services:

    # ModSecurity/nginx on 80 port.
    modsecurity-crs-3.3-nginx:
        image: "owasp/modsecurity-crs:3.3-nginx"
        restart: unless-stopped
        ports:
            - "80:80"  # HOST:CONTAINER
        volumes:
            - ./etc/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/conf.d:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
        networks:
            - default
