pipeline {

  environment {

    registry = "ma3310/node-app-hello"
      // credentials 是 Jenkins 函数
      DOCKER_PWD = credentials('ma3310@docker')
    }
    
    //
    agent {
      docker {
        image 'ma3310/node-app-hello'
        args '-p 3000:3000'
        args '-v $HOME:/root'
        args '-v /var/run/docker.sock:/var/run/docker.sock'
      }
    }

    options {
      skipStagesAfterUnstable()
    }

    stages {
      stage("Build"){
        steps {
          sh 'npm install'
        }
      }
      
      stage("Test"){
        steps {
          sh 'npm test'
        }
      }

      stage("Build & Push Docker image") {
        steps {
          sh 'docker image build -t $registry:$BUILD_NUMBER.'
          sh 'docker login -u gnschenker -p $DOCKER_PWD'
          sh 'docker image push $registry:$BUILD_NUMBER'
          sh "docker image rm $registry:$BUILD_NUMBER"
        }
      }
    }
  }
}
