# docker-compose uses local as volume: https://github.com/docker/compose/issues/2957
version: "3.4"

services:
    mod_auth_openidc:
        image: "ma3310/centos:7-oidc-2.4.x"
        restart: always
        volumes: 
            # Uncomment if certbot is being used.
            # - /etc/letsencrypt:/etc/letsencrypt
            - ./etc/httpd/conf:/etc/httpd/conf
            # If external certificate is being used, they could be put under conf.d/cert.
            - ./etc/httpd/conf.d:/etc/httpd/conf.d
            - ./etc/httpd/conf.modules.d:/etc/httpd/conf.modules.d
            - ./log:/var/log/httpd
        ports:
            - "80:80"
            - "443:443"
        network_mode: "bridge"
