# Deployed as local service.
version: "3.1"

services:

    mysql:
        image: "mysql:5.7"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
        network_mode: "host"
        