# 部署基于 redis:alpine 的 redis
# kubectl explain Deployment 检查支持的参数及其设定值
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels: 
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy: 
    type: "RollingUpdate" # "Recreate"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.5"
          limits:
            memory: "256Mi"
            cpu: "1"
        ports:
        - containerPort: 6379
          name: redis