kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-host-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  storageClassName:
    "standard"