# 需要 /data 目录
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-data
spec:
  storageClassName: "standard"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
